//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_Tutorial.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Sehr geehrte Anwenderin, sehr geehrter Anwender,

in diesem Tutorial werden Ihnen als neueinsteiger grundlegende Abfragen und Funktionen der Sprache SQL, Structured Query Language (strukturierte Abfragesprache), beigebracht. 

Wir wünschen Ihnen viel spaß, und vorallem erfolg, beim Lesen der Lektionen, und Lösen der Aufgaben")]
        public string Intro_Text {
            get {
                return ((string)(this["Intro_Text"]));
            }
            set {
                this["Intro_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mit den Aggregatfunktionen kannst Du statistische Auswertungen numerischer Daten " +
            "in einer Datenbank vornehmen. \r\nJede Aggregatfunktion wird auf ein Attribut eine" +
            "r Tabelle angewendet und liefert als Ergebnis einen Zahlenwert zurück.\r\nEs gibt " +
            "die 6 Aggregatfunktionen AVG, MAX, MIN, SUM, COUNTund DISTINCT\r\n\r\nHINWEIS: Ohne " +
            "die GROUP BY-Klausel kannst Du Aggregatfunktionen und die Auswahl von Attributen" +
            " nicht mischen. Die folgende select-Anweisung liefert also einen Fehler:\r\nSELECT" +
            " Artikelname, AVG(Einzelpreis) FROM Artikel\r\n\r\nDISTINCT (=engl. für eindeutig) M" +
            "it dem distinct-Operator sorgt man dafür, dass in der Ergebnistabelle keine Eint" +
            "räge mehrfach vorkommen. \r\n\r\nSUM (=engl. für Summe)\r\nDieser SQL-Befehl zählt die" +
            " aus der Abfrage resultierenden Zahlenwerte (numerischen Werte) der Spalte zusam" +
            "men, auf die er angewendet wird.\r\n\r\nCOUNT (=engl. für Anzahl)\r\nDieser Befehl zäh" +
            "lt die Anzahl der von NULL verschiedenen Werte einer Spalte in der Ergebnistabel" +
            "le. Alle Datensätze zählt man mit count(*). \r\nWill man nur die verschiedenen Wer" +
            "te einer Spalte zählen, so benutzt man count(DISTINCT Spaltenname). \r\n\r\nMAX() : " +
            "MAXIMUM (engl. für Maximum)\r\nMIN() : MINIMUM (engl. für Minimum)\r\nBenutzt man di" +
            "ese Befehle, so erhält man die größte/kleinste Zahl, also das Maximum/Minimum de" +
            "r Spalte. \r\n\r\nAVG() : AVERAGE (engl. für Mittelwert)\r\nÄhnlich wie MIN und MAX gi" +
            "bt uns AVG den Mittelwert (Durchschnitt) aller Zahlenwerte einer Spalte. Dabei w" +
            "erden alle Einträge addiert und dann durch die Anzahl der Einträge geteilt. ")]
        public string Lektion1_Text {
            get {
                return ((string)(this["Lektion1_Text"]));
            }
            set {
                this["Lektion1_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Admin")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Admin")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQL Tutorial")]
        public string Ueberschrift {
            get {
                return ((string)(this["Ueberschrift"]));
            }
            set {
                this["Ueberschrift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gib den durschschnittlichen einzelpreis von allen artikeln aus")]
        public string L1_Aufgabe1 {
            get {
                return ((string)(this["L1_Aufgabe1"]));
            }
            set {
                this["L1_Aufgabe1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gib an wie viele Bestellungen die Firma United Package insgesamgt ausgeliefert ha" +
            "t")]
        public string L1_Aufgabe2 {
            get {
                return ((string)(this["L1_Aufgabe2"]));
            }
            set {
                this["L1_Aufgabe2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gib die durchschnittlichen frachtkosten an")]
        public string L1_Aufgabe3 {
            get {
                return ((string)(this["L1_Aufgabe3"]));
            }
            set {
                this["L1_Aufgabe3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gib alle Kunden aus, die bei dem lieferanten \'Exotic Liquids\' mit einen mindestum" +
            "satz von 1000 bestellt haben")]
        public string L1_Aufgabe4 {
            get {
                return ((string)(this["L1_Aufgabe4"]));
            }
            set {
                this["L1_Aufgabe4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Arithmetische Operatoren führen mathematische Operationen für zwei Ausdrücke eines oder mehrerer Datentypen durch.
 Sie werden von der numerischen Datentypkategorie aus ausgeführt.
Operator                Bedeutung
+ (Addition) 	Addition
- (Subtraktion) 	Subtraktion
* (Multiplikation) 	Multiplikation
/ (Dividieren) 	Division

Mit den Operatoren Plus (+) und Minus (-) können auch arithmetische Operationen für datetime- und smalldatetime-Werte ausgeführt werden.
z.B. Wir können BestellteEinheiten und Lagerbestand  zusammen addieren
""SELECT (Lagerbestand+BestellteEinheiten) as Addition From Artikel""

Das Datum von Heute bekommt man mit DATE()")]
        public string Lektion2_Text {
            get {
                return ((string)(this["Lektion2_Text"]));
            }
            set {
                this["Lektion2_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Um Redundanzen beim Speichern zu vermeiden, werden die Informationen auf verschiedene Tabellen verteilt. Zur Erhaltung der logischen Zusammengehörigkeit werden Fremdschlüssel-Beziehungen zwischen den Tabellen aufgebaut.

Muss das Datenbanksystem eine Anfrage verarbeiten, bei der Informationen aus mehreren Tabellen benötigt werden, ist es erforderlich die einzelnen Datensätze der Tabellen wieder zusammenzuführen. 
Dadurch werden die ursprünglichen Informationen wiederhergestellt. Dies wird in SQL-Datenbanken mit Hilfe von SQL JOINS (Verbünden) umgesetzt. Mit einem SQL Join werden mehrere Tabellen verknüpft, die in einer Beziehung zueinander stehen.
Hier z.B. Wir werden die Tabellen Bestellungen und Bestelldetails verbinden:
""SELECT * FROM Bestellungen Inner Join Bestelldetails On Bestellungen.BestellNr=Bestelldetails.BestellNr""")]
        public string Lektion3_Text {
            get {
                return ((string)(this["Lektion3_Text"]));
            }
            set {
                this["Lektion3_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"GROUP BY 

Die Group By Funktion erweitert die aus Lektion 1 erlernten Aggregatfunktionen AVG(), SUM() etc.
Mit Ihr kann man ergebnisse aus diesen, mit anderen tabellen in einer Select anweisung ausgeben

zb: select LieferantenNr, avg(Einzelpreis) from Artikel group by LieferantenNr 
")]
        public string Lektion4_Text {
            get {
                return ((string)(this["Lektion4_Text"]));
            }
            set {
                this["Lektion4_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Das ist das text von Fünf Zwei")]
        public string Lektion5_Text {
            get {
                return ((string)(this["Lektion5_Text"]));
            }
            set {
                this["Lektion5_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LEKTION 1")]
        public string Lektion1_Titel {
            get {
                return ((string)(this["Lektion1_Titel"]));
            }
            set {
                this["Lektion1_Titel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LEKTION 2")]
        public string Lektion2_Titel {
            get {
                return ((string)(this["Lektion2_Titel"]));
            }
            set {
                this["Lektion2_Titel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LEKTION 3")]
        public string Lektion3_Titel {
            get {
                return ((string)(this["Lektion3_Titel"]));
            }
            set {
                this["Lektion3_Titel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LEKTION 4")]
        public string Lektion4_Titel {
            get {
                return ((string)(this["Lektion4_Titel"]));
            }
            set {
                this["Lektion4_Titel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LEKTION 5")]
        public string Lektion5_Titel {
            get {
                return ((string)(this["Lektion5_Titel"]));
            }
            set {
                this["Lektion5_Titel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("subtrahiere den Mindestbestand vom Lagerbestand,\r\nbei welchen artikeln muss das l" +
            "ager aufgefüllt werden ? \r\n")]
        public string L2_Aufgabe2 {
            get {
                return ((string)(this["L2_Aufgabe2"]));
            }
            set {
                this["L2_Aufgabe2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gib an wie alt die einzelnen bestellungeen sind")]
        public string L2_Aufgabe1 {
            get {
                return ((string)(this["L2_Aufgabe1"]));
            }
            set {
                this["L2_Aufgabe1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("multipliziere alle Bestellte Artikel multipliziert mit deren Einzelpreis  ")]
        public string L2_Aufgabe3 {
            get {
                return ((string)(this["L2_Aufgabe3"]));
            }
            set {
                this["L2_Aufgabe3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gib an wie viel rabatt(€) man durch den Rabatt(%) auf die einzelnen bestellungen " +
            "in bestelldetails bekommt\r\n")]
        public string L2_Aufgabe4 {
            get {
                return ((string)(this["L2_Aufgabe4"]));
            }
            set {
                this["L2_Aufgabe4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gib das Bestelldatum und den dazugehörigen Einzelpreis an.\r\n")]
        public string L3_Aufgabe1 {
            get {
                return ((string)(this["L3_Aufgabe1"]));
            }
            set {
                this["L3_Aufgabe1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gib die Versandfirmen Namen und das Lieferdatum von deren Lieferungen an\r\n")]
        public string L3_Aufgabe2 {
            get {
                return ((string)(this["L3_Aufgabe2"]));
            }
            set {
                this["L3_Aufgabe2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gib die Artikelnamen und deren passende kategorienamen an")]
        public string L3_Aufgabe3 {
            get {
                return ((string)(this["L3_Aufgabe3"]));
            }
            set {
                this["L3_Aufgabe3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gib die Lieferantenfirmen und die Artikelnamen an, die sie Liefern")]
        public string L3_Aufgabe4 {
            get {
                return ((string)(this["L3_Aufgabe4"]));
            }
            set {
                this["L3_Aufgabe4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gib alle Firmen aus, und deren Durschschnittlichen Artikelpreis, ordne die ausgab" +
            "e aufsteigend nach dem einzelpreis")]
        public string L4_Aufgabe1 {
            get {
                return ((string)(this["L4_Aufgabe1"]));
            }
            set {
                this["L4_Aufgabe1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gib den Durchschnittlichen Frachtkostenpreis für jedn kunden an, ordne die ausgab" +
            "e aufsteigend nach kunden firma")]
        public string L4_Aufgabe2 {
            get {
                return ((string)(this["L4_Aufgabe2"]));
            }
            set {
                this["L4_Aufgabe2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Frage3 von L4")]
        public string L4_Aufgabe3 {
            get {
                return ((string)(this["L4_Aufgabe3"]));
            }
            set {
                this["L4_Aufgabe3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Frage4 von L4")]
        public string L4_Aufgabe4 {
            get {
                return ((string)(this["L4_Aufgabe4"]));
            }
            set {
                this["L4_Aufgabe4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Frage1 von L5")]
        public string L5_Aufgabe1 {
            get {
                return ((string)(this["L5_Aufgabe1"]));
            }
            set {
                this["L5_Aufgabe1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Frage2 von L5")]
        public string L5_Aufgabe2 {
            get {
                return ((string)(this["L5_Aufgabe2"]));
            }
            set {
                this["L5_Aufgabe2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Frage3 von L5")]
        public string L5_Aufgabe3 {
            get {
                return ((string)(this["L5_Aufgabe3"]));
            }
            set {
                this["L5_Aufgabe3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Frage4 von L5")]
        public string L5_Aufgabe4 {
            get {
                return ((string)(this["L5_Aufgabe4"]));
            }
            set {
                this["L5_Aufgabe4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT avg(Einzelpreis) AS avgEinzelpreis FROM Artikel")]
        public string L1_Loesung1 {
            get {
                return ((string)(this["L1_Loesung1"]));
            }
            set {
                this["L1_Loesung1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT count(bestellnr) AS insgesamt_ausgeliefert FROM versandfirmen INNER JOIN b" +
            "estellungen ON versandfirmen.firmennr=bestellungen.versandüber WHERE firma=\'unit" +
            "ed package\'")]
        public string L1_Loesung2 {
            get {
                return ((string)(this["L1_Loesung2"]));
            }
            set {
                this["L1_Loesung2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT avg(frachtkosten) AS frachtkosten FROM bestellungen")]
        public string L1_Loesung3 {
            get {
                return ((string)(this["L1_Loesung3"]));
            }
            set {
                this["L1_Loesung3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT a.artikelname, k.kategoriename FROM artikel a, kategorien k WHERE k.katego" +
            "rienr=a.kategorienr ORDER BY k.kategoriename asc ")]
        public string L1_Loesung4 {
            get {
                return ((string)(this["L1_Loesung4"]));
            }
            set {
                this["L1_Loesung4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select bestellNr, DATE() - bestelldatum as Tage from bestellungen")]
        public string L2_Loesung1 {
            get {
                return ((string)(this["L2_Loesung1"]));
            }
            set {
                this["L2_Loesung1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select artikelname From Artikel where (lagerbestand- mindestbestand) <= 0 ")]
        public string L2_Loesung2 {
            get {
                return ((string)(this["L2_Loesung2"]));
            }
            set {
                this["L2_Loesung2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Einzelpreis * Anzahl From Bestelldetails")]
        public string L2_Loesung3 {
            get {
                return ((string)(this["L2_Loesung3"]));
            }
            set {
                this["L2_Loesung3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select bestellnr, (anzahl*Einzelpreis)*Rabatt as \'Rabatt(€)\' From Bestelldetails " +
            "Where Rabatt>0 order by bestellnr")]
        public string L2_Loesung4 {
            get {
                return ((string)(this["L2_Loesung4"]));
            }
            set {
                this["L2_Loesung4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT Bestelldatum,Einzelpreis From Bestellungen Inner Join Bestelldetails On Be" +
            "stellungen.BestellNr=Bestelldetails.BestellNr")]
        public string L3_Loesung1 {
            get {
                return ((string)(this["L3_Loesung1"]));
            }
            set {
                this["L3_Loesung1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select bestellNr, Firma, Lieferdatum From Versandfirmen Inner Join Bestellungen O" +
            "n Versandfirmen.FirmenNr=Bestellungen.versandÜber order by bestellnr")]
        public string L3_Loesung2 {
            get {
                return ((string)(this["L3_Loesung2"]));
            }
            set {
                this["L3_Loesung2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Kategoriename,Artikelname From Kategorien Inner Join Artikel On Kategorien" +
            ".KategorieNr=Artikel.KategorieN")]
        public string L3_Loesung3 {
            get {
                return ((string)(this["L3_Loesung3"]));
            }
            set {
                this["L3_Loesung3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Firma,Artikelname From Lieferanten Inner Join Artikel On Lieferanten.Liefe" +
            "rantenNr =Artikel.LieferantenNr")]
        public string L3_Loesung4 {
            get {
                return ((string)(this["L3_Loesung4"]));
            }
            set {
                this["L3_Loesung4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select l.Firma, AVG(a.Einzelpreis) as avgEinzelpreis From Artikel a Inner Join Li" +
            "eferanten l ON a.LieferantenNr=l.LieferantenNr Group By l.Firma order by avg(a.e" +
            "inzelpreis)")]
        public string L4_Loesung1 {
            get {
                return ((string)(this["L4_Loesung1"]));
            }
            set {
                this["L4_Loesung1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string L4_Loesung2 {
            get {
                return ((string)(this["L4_Loesung2"]));
            }
            set {
                this["L4_Loesung2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string L4_Loesung3 {
            get {
                return ((string)(this["L4_Loesung3"]));
            }
            set {
                this["L4_Loesung3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string L4_Loesung4 {
            get {
                return ((string)(this["L4_Loesung4"]));
            }
            set {
                this["L4_Loesung4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string L4_Loesung5 {
            get {
                return ((string)(this["L4_Loesung5"]));
            }
            set {
                this["L4_Loesung5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string L5_Loesung1 {
            get {
                return ((string)(this["L5_Loesung1"]));
            }
            set {
                this["L5_Loesung1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string L5_Loesung2 {
            get {
                return ((string)(this["L5_Loesung2"]));
            }
            set {
                this["L5_Loesung2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string L5_Loesung3 {
            get {
                return ((string)(this["L5_Loesung3"]));
            }
            set {
                this["L5_Loesung3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string L5_Loesung4 {
            get {
                return ((string)(this["L5_Loesung4"]));
            }
            set {
                this["L5_Loesung4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string L5_Loesung5 {
            get {
                return ((string)(this["L5_Loesung5"]));
            }
            set {
                this["L5_Loesung5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nordwind.accdb")]
        public string DB_Path {
            get {
                return ((string)(this["DB_Path"]));
            }
            set {
                this["DB_Path"] = value;
            }
        }
    }
}
